version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ixtore
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5000:5432"